
package soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PetClinicServiceImplService", targetNamespace = "http://service.soap/", wsdlLocation = "http://localhost:6666/myservice?wsdl")
public class PetClinicServiceImplService
    extends Service
{

    private final static URL PETCLINICSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PETCLINICSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PETCLINICSERVICEIMPLSERVICE_QNAME = new QName("http://service.soap/", "PetClinicServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6666/myservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PETCLINICSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PETCLINICSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PetClinicServiceImplService() {
        super(__getWsdlLocation(), PETCLINICSERVICEIMPLSERVICE_QNAME);
    }

    public PetClinicServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PETCLINICSERVICEIMPLSERVICE_QNAME, features);
    }

    public PetClinicServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PETCLINICSERVICEIMPLSERVICE_QNAME);
    }

    public PetClinicServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PETCLINICSERVICEIMPLSERVICE_QNAME, features);
    }

    public PetClinicServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PetClinicServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PetClinicServiceInterface
     */
    @WebEndpoint(name = "PetClinicServiceImplPort")
    public PetClinicServiceInterface getPetClinicServiceImplPort() {
        return super.getPort(new QName("http://service.soap/", "PetClinicServiceImplPort"), PetClinicServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PetClinicServiceInterface
     */
    @WebEndpoint(name = "PetClinicServiceImplPort")
    public PetClinicServiceInterface getPetClinicServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap/", "PetClinicServiceImplPort"), PetClinicServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PETCLINICSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PETCLINICSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PETCLINICSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
