
package soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PetClinicServiceInterface", targetNamespace = "http://service.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PetClinicServiceInterface {


    /**
     * 
     * @return
     *     returns java.util.List<soap.service.Doctor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDoctors", targetNamespace = "http://service.soap/", className = "soap.service.GetAllDoctors")
    @ResponseWrapper(localName = "getAllDoctorsResponse", targetNamespace = "http://service.soap/", className = "soap.service.GetAllDoctorsResponse")
    @Action(input = "http://service.soap/PetClinicServiceInterface/getAllDoctorsRequest", output = "http://service.soap/PetClinicServiceInterface/getAllDoctorsResponse")
    public List<Doctor> getAllDoctors();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws DoctorNotFoundException_Exception
     * @throws WorkdayNotFreeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addWorkday", targetNamespace = "http://service.soap/", className = "soap.service.AddWorkday")
    @ResponseWrapper(localName = "addWorkdayResponse", targetNamespace = "http://service.soap/", className = "soap.service.AddWorkdayResponse")
    @Action(input = "http://service.soap/PetClinicServiceInterface/addWorkdayRequest", output = "http://service.soap/PetClinicServiceInterface/addWorkdayResponse", fault = {
        @FaultAction(className = WorkdayNotFreeException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/addWorkday/Fault/WorkdayNotFreeException"),
        @FaultAction(className = DoctorNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/addWorkday/Fault/DoctorNotFoundException")
    })
    public void addWorkday(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Workday arg1)
        throws DoctorNotFoundException_Exception, WorkdayNotFreeException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws DoctorNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorLastName", targetNamespace = "http://service.soap/", className = "soap.service.GetDoctorLastName")
    @ResponseWrapper(localName = "getDoctorLastNameResponse", targetNamespace = "http://service.soap/", className = "soap.service.GetDoctorLastNameResponse")
    @Action(input = "http://service.soap/PetClinicServiceInterface/getDoctorLastNameRequest", output = "http://service.soap/PetClinicServiceInterface/getDoctorLastNameResponse", fault = {
        @FaultAction(className = DoctorNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/getDoctorLastName/Fault/DoctorNotFoundException")
    })
    public List<String> getDoctorLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws DoctorNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soap.service.Workday>
     * @throws DoctorNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorScheduleByLastName", targetNamespace = "http://service.soap/", className = "soap.service.GetDoctorScheduleByLastName")
    @ResponseWrapper(localName = "getDoctorScheduleByLastNameResponse", targetNamespace = "http://service.soap/", className = "soap.service.GetDoctorScheduleByLastNameResponse")
    @Action(input = "http://service.soap/PetClinicServiceInterface/getDoctorScheduleByLastNameRequest", output = "http://service.soap/PetClinicServiceInterface/getDoctorScheduleByLastNameResponse", fault = {
        @FaultAction(className = DoctorNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/getDoctorScheduleByLastName/Fault/DoctorNotFoundException")
    })
    public List<Workday> getDoctorScheduleByLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws DoctorNotFoundException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws TimeSlotIsNotFreeException_Exception
     * @throws WorkdayNotFoundException_Exception
     * @throws TimeSlotNotFoundException_Exception
     * @throws DoctorNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "registerNewPatient", targetNamespace = "http://service.soap/", className = "soap.service.RegisterNewPatient")
    @ResponseWrapper(localName = "registerNewPatientResponse", targetNamespace = "http://service.soap/", className = "soap.service.RegisterNewPatientResponse")
    @Action(input = "http://service.soap/PetClinicServiceInterface/registerNewPatientRequest", output = "http://service.soap/PetClinicServiceInterface/registerNewPatientResponse", fault = {
        @FaultAction(className = TimeSlotNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/registerNewPatient/Fault/TimeSlotNotFoundException"),
        @FaultAction(className = TimeSlotIsNotFreeException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/registerNewPatient/Fault/TimeSlotIsNotFreeException"),
        @FaultAction(className = DoctorNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/registerNewPatient/Fault/DoctorNotFoundException"),
        @FaultAction(className = WorkdayNotFoundException_Exception.class, value = "http://service.soap/PetClinicServiceInterface/registerNewPatient/Fault/WorkdayNotFoundException")
    })
    public void registerNewPatient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws DoctorNotFoundException_Exception, TimeSlotIsNotFreeException_Exception, TimeSlotNotFoundException_Exception, WorkdayNotFoundException_Exception
    ;

}
