
package soap.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TimeSlotIsNotFreeException", targetNamespace = "http://service.soap/")
public class TimeSlotIsNotFreeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TimeSlotIsNotFreeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TimeSlotIsNotFreeException_Exception(String message, TimeSlotIsNotFreeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TimeSlotIsNotFreeException_Exception(String message, TimeSlotIsNotFreeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.service.TimeSlotIsNotFreeException
     */
    public TimeSlotIsNotFreeException getFaultInfo() {
        return faultInfo;
    }

}
