
package soap.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TimeSlotNotFoundException", targetNamespace = "http://service.soap/")
public class TimeSlotNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TimeSlotNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TimeSlotNotFoundException_Exception(String message, TimeSlotNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TimeSlotNotFoundException_Exception(String message, TimeSlotNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.service.TimeSlotNotFoundException
     */
    public TimeSlotNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
